### PR TITLE
Chess game cpp demo

### PR DESCRIPTION
**Pull request by itArnaudov**
v2.1a

### CODE REVIEW

**Review by itArnaudov — COMMENTED** [review]
ok

**Review by itArnaudov — COMMENTED** [review]
nice

**Review by itArnaudov — COMMENTED** [review]
working

**Review by itArnaudov — COMMENTED** [review]
accepted

**Review by itArnaudov — COMMENTED** [review]
okay

**Review by itArnaudov — COMMENTED** [review]
approve

**Review by itArnaudov — COMMENTED** [review]
good

**Review by itArnaudov — COMMENTED** [review]
done

**Review by itArnaudov — COMMENTED** [review]
better

**Review by itArnaudov — COMMENTED** [review]
complete

**Review by itArnaudov — COMMENTED** [review]
allowed

**Review by Ivan-CBRE — COMMENTED** [review]
creative

**Review by Ivan-CBRE — COMMENTED** [review]
thrifty

**Review by Ivan-CBRE — COMMENTED** [review]
awesome

**Review by Ivan-CBRE — COMMENTED** [review]
accept

**Review by Ivan-CBRE — COMMENTED** [review]
better

**Review by Ivan-CBRE — COMMENTED** [review]
improvement

**Pull request merged**
