### PR TITLE
applied final Fix code section format in readme md

### PR DESCRIPTION
**Pull request by itArnaudov**
thanks to contributors for adding in a fix for our issue. merging code now into main branch

### CODE REVIEW

**Review by Ivan-CBRE — COMMENTED** [review]
looks sleek, should be good to merge those changes. best.

**Review by Ivan-CBRE — APPROVED** [review]
awesome fix, glad it's working in test. ready to merge with main branch as required. thx.

**Review by itArnaudov — COMMENTED** [review]
okay

**Review by Ivan-CBRE — COMMENTED** [review]
good

**Review by Ivan-CBRE — COMMENTED** [review]
ok

**Review by Ivan-CBRE — COMMENTED** [review]
allow

**Review by Ivan-CBRE — COMMENTED** [review]
view

**Review by Ivan-CBRE — COMMENTED** [review]
great

**Pull request merged**
